// <auto-generated />
namespace API_TUTORS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class my_mig : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(my_mig));
        
        string IMigrationMetadata.Id
        {
            get { return "201907271919547_my_mig"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
